name: geobingan_v2_app
description: geoBingAn v2 Mobile App - Natural language reporting with AI assistance
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # API & Networking
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.1
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Gemini AI
  google_generative_ai: ^0.2.0
  
  # Chat UI
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.3
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.3.1
  url_launcher: ^6.2.2
  http: ^1.1.0
  flutter_web_auth_2: ^3.0.4
  connectivity_plus: ^5.0.2
  
  # Image & File
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Audio Recording
  record: ^5.0.4
  
  # Environment Configuration
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/